[build]
  command = "npm install"  # Install any necessary Node.js packages
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "2.8.0"  # Specify the Flutter version you want to use

[build.lifecycle]
  before_build = ["./install_flutter.sh"]

[context.production]
  command = "npm run build"
  publish = "build/web"
