[build]
  command = "flutter build web"
  publish = "build/web"

[context.production]
  command = "flutter build web --release"
  publish = "build/web"

[context.deploy-preview]
  command = "flutter build web --release"
  publish = "build/web"
